
API_TITLE = "Moneypenny API"
API_VERSION = "v0.1.0"
OPENAPI_VERSION = "3.0.3"
OPENAPI_JSON_PATH = "openapi/moneypenny.json"
OPENAPI_URL_PREFIX = "/"
OPENAPI_REDOC_PATH = "/redoc"
OPENAPI_REDOC_URL = "https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js"  # noqa: E501
OPENAPI_SWAGGER_UI_PATH = "/docs/moneypenny"
OPENAPI_SWAGGER_UI_URL = "https://cdn.jsdelivr.net/npm/swagger-ui-dist/"

[development]
FLASK_DEBUG = true

[production]
FLASK_DEBUG = false
